# Generated by Django 5.1 on 2024-10-20 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.turno'),
        ),
    ]
