# Generated by Django 5.1 on 2024-10-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_pago_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
