# Generated by Django 5.1 on 2024-10-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_remove_turno_usuario_turno_cliente_turno_profesional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
