# Generated by Django 5.1 on 2024-09-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
