# Generated by Django 5.1 on 2024-09-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
